'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const raiz = path.resolve(__dirname, '..');
const dom = new JSDOM(fs.readFileSync(path.join(raiz,'www/index.html'),'utf8'), { runScripts:'outside-only' });
const w = dom.window;
const controles = [...w.document.querySelectorAll('input,select,textarea')];
w.eval(fs.readFileSync(path.join(raiz,'www/js/form-layout.js'),'utf8'));
w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
assert.ok(controles.every(el => el.isConnected), 'Controles antigos permanecem para não apagar dados ao editar');
['os-observacoes','compra-vendedor-rg','compra-vendedor-endereco','compra-aparelho-imei2','compra-conta-email-senha','compra-observacoes']
  .forEach(id => assert.ok(w.document.getElementById(id).closest('.form-retirado'), id));
['os-valor','os-status','os-data-prevista','os-assinar-depois','os-nao-assinado','entrega-assinar-depois','entrega-nao-assinado']
  .forEach(id => assert.equal(w.document.getElementById(id).closest('details,.form-retirado'), null, id));
const app = fs.readFileSync(path.join(raiz,'www/js/app.js'),'utf8');
const inicio = app.indexOf('  function montarObjetoOS() {');
const fim = app.indexOf('\n  // Resolve o valor de garantia', inicio);
assert.ok(inicio > 0 && fim > inicio);
w.eval(fs.readFileSync(path.join(raiz,'www/js/validacao.js'),'utf8'));
w.texto = id => w.document.getElementById(id)?.value || '';
w.checkboxesMarcados = seletor => [...w.document.querySelectorAll(seletor+':checked')].map(n=>n.value);
w.garantiaDiasResolvida = () => 90;
w.assinarDepoisMarcado = () => false;
w.naoAssinadoMarcado = () => true;
w.ConfigApp = { carregarConfig: () => ({}) };
w.emEdicaoHistorico = true;
w.osAtual = { diagnosticoTecnico:{diagnostico:'Anotação anterior',solucao:'Reparo salvo',pecasTrocar:[{nome:'Tela',valor:80}]} };
w.eval(app.slice(inicio,fim));
Object.entries({'cliente-nome':'Cliente teste','cliente-telefone':'27999990000','aparelho-marca':'Motorola','aparelho-modelo':'Moto G','aparelho-defeito':'Tela danificada','os-valor':'250.75','os-status':'Em reparo','os-data-prevista':'2026-09-15'})
  .forEach(([id,v])=>{w.document.getElementById(id).value=v;});
const dados = w.montarObjetoOS();
assert.equal(dados.valor,'250.75');
assert.equal(dados.status,'Em reparo');
assert.equal(dados.diagnosticoTecnico.solucao,'Reparo salvo');
assert.equal(dados.diagnosticoTecnico.pecasTrocar[0].valor,80);
assert.equal(dados.naoAssinado,true);
assert.equal(w.SistemaOSValidacao.validarDadosOS(dados),null);
const mapper = require('../www/js/supabase/os-service.js');
const envio = mapper._dadosParaCriacao(dados);
assert.equal(Number(envio.valor),250.75);
assert.equal(envio.status,'Em reparo');
assert.equal(envio.data_prevista,'2026-09-15');
assert.equal(envio.dados_extras.nao_assinado,true);
dados.valor=-1;
assert.ok(w.SistemaOSValidacao.validarDadosOS(dados).valor);
dom.window.close();
console.log('OK: formulário simplificado preserva os dados antigos e envia valor, status, prazo e não assinado corretamente.');
